server:
  port: 8761

Spring:
  output:
    ansi:
      enabled: Always

ead:
  serviceRegistry:
    username: ${EUREKA_SERVICE_USERNAME}
    password: ${EUREKA_SERVICE_PASSWORD}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka/eureka'